<a href="https://colab.research.google.com/github/fargonemaciel/infnet-machine-learning-codes/blob/main/fargone_maciel_flor_PB_TP1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Projeto de Bloco: Inteligência Artificial e Machine Learning [26E1_5]

### Teste de Performance - TP1

Chegamos em uma das etapas de preparação! A cada Teste de Performance (TP) você terá a oportunidade de praticar os conhecimentos adquiridos e receber feedbacks relevantes para o seu aprendizado.

Objetivo: Este projeto propõe uma experiência prática em Inteligência Artificial (IA) e Machine Learning (ML), permitindo a aplicação de conceitos e técnicas adquiridos em disciplinas regulares num contexto de dados reais.

Base de dados: [Titanic - Machine Learning from Disaster](https://www.kaggle.com/competitions/titanic/data)

Descrição das Atividades:

1. **Carregamento de Dados**: Identifique as características (features) e o alvo (target) nos conjuntos de dados, compreendendo sua estrutura e importância.
2. **Divisão de Dados**: Separe os dados em conjuntos de treino e validação, essenciais para o desenvolvimento e avaliação de modelos de ML. Você irá dividir 80% dos dados para treino e o restante para validação.
3. **Transformação de Dados**: Utilize transformadores do Scikit-Learn para ajustar e padronizar as variáveis dos dados.
4. **Modelagem de K-Nearest Neighbors (KNN)**: Implemente e ajuste o algoritmo KNN, compreendendo suas nuances e aplicabilidade.
5. **Avaliação de Modelos**: Avalie a qualidade do modelo desenvolvido usando acurácia
6. **Análise de Parâmetros**: Explore diferentes valores para o parâmetro K do KNN e analise seu impacto nos resultados obtidos (através da acurácia do modelo para os dados de validação).

In [71]:
# Imports de Bibliotecas
import pandas as pd

from sklearn import preprocessing, neighbors, model_selection, metrics
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score

In [45]:
link = '/content/drive/MyDrive/Colab Notebooks/Arquives/titanic/train.csv'

df_titanic = pd.read_csv(link)
df_titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [46]:
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [47]:
df_titanic.isnull().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

In [48]:
df_titanic['Cabin'] = df_titanic['Cabin'].fillna('Unknown')
df_titanic['Embarked'] = df_titanic['Embarked'].fillna('Unknown')
df_titanic['Age'] = df_titanic['Age'].fillna(df_titanic['Age'].median())

In [49]:
df_titanic.isnull().sum().sort_values(ascending=False)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [50]:
feature_list = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked']
# As features escolhidas são importantes para uma primeira análise exploratória de dados e estudo de correlação entre elas e entre estas e a variável target.
# Temos informações importantes como a classe do passageiro, o portão de embarque e relações familiares que podem mostrar algum padrão digno de nota.

target = ['Survived']
# E como variável target, temos o binário se o passageiro sobreviveu ao acidente ou não.

In [51]:
# Separação dos Dados em Teste e Validação/Teste

xtrn, xtst = model_selection.train_test_split(df_titanic, test_size=0.2, stratify=df_titanic[target])

print(xtrn.shape)
print(xtst.shape)

(712, 12)
(179, 12)

In [52]:
print(xtrn[feature_list])

     Pclass     Sex   Age  SibSp  Parch      Fare    Cabin Embarked
615       2  female  24.0      1      2   65.0000  Unknown        S
352       3    male  15.0      1      1    7.2292  Unknown        C
51        3    male  21.0      0      0    7.8000  Unknown        S
599       1    male  49.0      1      0   56.9292      A20        C
39        3  female  14.0      1      0   11.2417  Unknown        C
..      ...     ...   ...    ...    ...       ...      ...      ...
339       1    male  45.0      0      0   35.5000        T        S
186       3  female  28.0      1      0   15.5000  Unknown        Q
646       3    male  19.0      0      0    7.8958  Unknown        S
737       1    male  35.0      0      0  512.3292     B101        C
361       2    male  29.0      1      0   27.7208  Unknown        C

[712 rows x 8 columns]

In [53]:
xtst.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
317,318,0,2,"Moraweck, Dr. Ernest",male,54.0,0,0,29011,14.000,Unknown,S
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.525,Unknown,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.000,Unknown,S
460,461,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.550,E12,S
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.0,1,1,C.A. 33112,36.750,Unknown,S

In [58]:
var_cat_encoding = ['Sex', 'Cabin', 'Embarked']

In [62]:
encoder = LabelEncoder()

for var in var_cat_encoding:
  xtrn[var] = encoder.fit_transform(xtrn[var])

for var in var_cat_encoding:
  xtst[var] = encoder.fit_transform(xtst[var])

In [63]:
xtrn.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
615,616,1,2,"Herman, Miss. Alice",0,24.0,1,2,220845,65.0000,123,2
352,353,0,3,"Elias, Mr. Tannous",1,15.0,1,1,2695,7.2292,123,0
51,52,0,3,"Nosworthy, Mr. Richard Cater",1,21.0,0,0,A/4. 39886,7.8000,123,2
599,600,1,1,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",1,49.0,1,0,PC 17485,56.9292,3,0
39,40,1,3,"Nicola-Yarred, Miss. Jamila",0,14.0,1,0,2651,11.2417,123,0

In [64]:
xtst.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
317,318,0,2,"Moraweck, Dr. Ernest",1,54.0,0,0,29011,14.000,41,2
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",1,9.0,0,2,363291,20.525,41,2
302,303,0,3,"Johnson, Mr. William Cahoone Jr",1,19.0,0,0,LINE,0.000,41,2
460,461,1,1,"Anderson, Mr. Harry",1,48.0,0,0,19952,26.550,31,2
549,550,1,2,"Davies, Master. John Morgan Jr",1,8.0,1,1,C.A. 33112,36.750,41,2

In [65]:
# Transformação/Padronização dos Dados

scaler = preprocessing.StandardScaler()
scaler.fit(xtrn[feature_list])

normed_trn = scaler.transform(xtrn[feature_list])
normed_tst = scaler.transform(xtst[feature_list])

In [66]:
# Treinamento utilizando Modelo KNN

knn = neighbors.KNeighborsClassifier(n_neighbors=3)
knn.fit(normed_trn, xtrn[target])

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [67]:
# Aplicando o Modelo de Predição

pred_trn = knn.predict(normed_trn)
pred_tst = knn.predict(normed_tst)

print(pred_trn)
print(pred_tst)

[1 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0
 1 0 0 1 1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 1 0
 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 1 1
 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0
 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 1 1
 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1
 0 0 1 0 1 0 1 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1
 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 1 0
 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 0 1 0 0 1 0 1 1 0
 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0
 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1
 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 1
 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0 0 1 0
 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1
 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 1 1
 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 1 0 0 0
 1 1 1 1 0 1 0 1 0]
[0 1 1 0 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0
 1 1 0 0 1 1 0 1 1 1 1 1 1 1 0 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1 1 0 1 0 1
 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 0 1 1 1
 1 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1
 0 1 1 1 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0 1 0 1 1 1]

In [73]:
# Acurácia do Modelo

acc_trn = metrics.accuracy_score(xtrn[target], pred_trn)
acc_tst = metrics.accuracy_score(xtst[target], pred_tst)

print(acc_trn)
print(acc_tst)

# O modelo está performando melhor apenas na base de treino, mas no teste tem baixa acurácia, podendo indicar um baixo k do modelo ou ainda overfitting
# com os dados de trieno.

0.8679775280898876
0.5698324022346368

In [75]:
# Testando vários valores de K e comparando os resultados

n_neighbors = [1, 3, 5, 7, 9, 11, 13, 15]

results = []

for k in n_neighbors:
  knn = neighbors.KNeighborsClassifier(n_neighbors=k)
  knn.fit(normed_trn, xtrn[target])
  pred_trn = knn.predict(normed_trn)
  pred_tst = knn.predict(normed_tst)
  acc_trn = metrics.accuracy_score(xtrn[target], pred_trn)
  acc_tst = metrics.accuracy_score(xtst[target], pred_tst)
  results.append([k, acc_trn, acc_tst])

results = pd.DataFrame(results, columns=['K', 'Acurácia Treino', 'Acurácia Teste'])
results

# Agora a acurácia mostra uma melhora significativa para um K maior

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

    K  Acurácia Treino  Acurácia Teste
0   1         0.984551        0.581006
1   3         0.867978        0.569832
2   5         0.858146        0.653631
3   7         0.848315        0.770950
4   9         0.844101        0.765363
5  11         0.837079        0.843575
6  13         0.838483        0.815642
7  15         0.837079        0.821229